import React from "react";
import { Card, Icon, Segment } from "semantic-ui-react";

const GenericContainer = ({
  ChildComponent,
  title,
  description,
  dateUpdated,
  loading,
}) => {
  return (
    <Card fluid as={Segment} loading={loading}>
      <Card.Content>
        <Card.Header>{title}</Card.Header>
        <Card.Meta>{description}</Card.Meta>
        <Card.Description textAlign="center">{ChildComponent}</Card.Description>
      </Card.Content>
      <Card.Content extra>
        <Icon name="line graph" />
        Generated by @VaccineStatusUK &nbsp; &nbsp;
        <Icon name="database" />
        <b>Data Source</b>: Public Health England (Updated {dateUpdated})
      </Card.Content>
    </Card>
  );
};

export default GenericContainer;
